#!/bin/sh

# Count emails, run mbsync and then compare email count to previous to determine if
# there's any new mail - if there is run neomutt then notmuch.

count_emails() {
    echo $(find ~/documents/.mail | wc -l)
}

num_files=$(count_emails)
mbsync -c "/home/finners/.config/mbsync/mbsyncrc" -a
if [ $(count_emails) != "$num_files" ]; then
    neomutt;
    notmuch new 2&>/dev/null;
fi
