#!/bin/bash

# Prints the lyric file corresponding to cmus's currently playing to the command line. If there isn't one gives option to:
# Create lyrics - Which opens up filepath in $EDITOR
# Mark file as instrumental - Which creates file with 'Instrumental' written to it
# Edit argument opens lyric file for editing


display_lyrics () {
    clear
    echo
    echo "$title" - "$artist"
    echo 
    echo
    cat "$filepath"
    echo
    echo
    echo {Pass the -e/--edit argument to edit these lyrics}
    echo
}

file_creation_options () {
    echo No lyrics for "$title" - "$artist" found
    read -t 10 -p "(C)reate Lyrics, (M)ark as Instrumental or (Q)uit: " response 
    if [[ "$response" =~ ('c'|'C'|'Create') ]] ; then
        $EDITOR "$filepath" && display_lyrics

    elif [[ "$response" =~ ('m'|'M'|'mark') ]] ; then
        echo "Instrumental" >> "$filepath" && display_lyrics
    
    else
        clear
    fi
}

lyrics_directory=~/music/lyrics/
currently_playing="$(cmus-remote -C status)"
title=$(echo "$currently_playing" | grep -m 1 'tag title' | cut -d ' ' -f 3-)
artist=$(echo "$currently_playing" | grep -m 1 'tag artist' | cut -d ' ' -f 3-)
filepath=""$lyrics_directory""$artist"-"$title""

if [[ $1 =~ ('-e'|'--edit') ]] ; then
    $EDITOR "$filepath" && display_lyrics

elif [[ -e "$filepath" ]] ; then
    display_lyrics
else
    file_creation_options
fi
