#!/bin/bash

# Prints the lyric file corresponding to cmus's currently playing to the command line. If there isn't one gives option to:
# Write lyrics - Which opens up filepath in $EDITOR
# Instrumental - Which creates file with 'Instrumental' written to it
# Search - Which opens a Genius formatted url looking for the song
# Edit argument opens lyric file for editing


display_lyrics () {
    clear
    echo
    echo "$title" - "$artist"
    echo 
    echo
    cat "$filepath"
    echo
    echo
    echo {Pass the -e/--edit argument to edit these lyrics}
    echo
}

file_creation_options () {
    echo No lyrics for "$title" - "$artist" found
    read -t 10 -p "(i)nstrumental, (w)rite lyrics, (s)earch lyrics: " response 
    case $response in
        "w"|"write")
            $EDITOR "$filepath" && display_lyrics
            ;;
        "i"|"instrumental")
            echo "Instrumental" >> "$filepath" && display_lyrics
            ;;
        "s"|"search")
            lyrics_search && $EDITOR "$filepath" && display_lyrics
    esac
}        

lyrics_search () {
    genius_search_url="$(echo "$artist"-"$title-lyrics" |
        tr '[:upper:]' '[:lower:]' |
        sed 's/ /-/g' |
        sed "s/'//g" |
        sed 's/\.//g' |
        sed 's|/|-|g' |
        sed 's/./\U&/')"
    $BROWSER "https://genius.com/$genius_search_url"
}


if [ -z "$(pidof cmus)" ] ; then
    echo "cmus not currently running" && exit 0
fi

lyrics_directory=~/music/lyrics/
currently_playing="$(cmus-remote -C status)"
title=$(echo "$currently_playing" | grep -m 1 'tag title' | cut -d ' ' -f 3-)
artist=$(echo "$currently_playing" | grep -m 1 'tag artist' | cut -d ' ' -f 3-)
filepath=""$lyrics_directory""$artist"-"$title""

if [[ $1 =~ ('-e'|'--edit') ]] ; then
    $EDITOR "$filepath" && display_lyrics

elif [[ -e "$filepath" ]] ; then
    display_lyrics
else
    file_creation_options
fi
