#!/bin/bash

# Start downloading torrent from clipboard magnet link and send notification

clipboard=$(xclip -selection c -o)
daemon_status=$(pidof transmission-daemon)
if ! [[ "$daemon_status" ]]; then
    transmission-daemon > /dev/null; sleep 0.2
fi 

success=$(transmission-remote -a "$clipboard" | grep "success")
if [ "$success" ] ; then
    $(notify-send -t 2000 "Magnet link added.")
else
    $(notify-send -t 2000 "Invalid link.")
fi
