#!/bin/sh

# Count emails, run mbsync and then compare email count to previous to determine if
# there's any new mail. If there is, run notmuch and then neomutt

count_emails() {
    echo $(find ~/documents/.mail | wc -l)
}

num_files=$(count_emails)
echo $num_files
mbsync -c "/home/finners/.config/mbsync/mbsyncrc" -a
if [ $(count_emails) != "$num_files" ]; then
    notmuch new 2&>/dev/null;
    neomutt;
fi
