#!/usr/bin/env bash

shopt -s nullglob globstar


prefix=${PASSWORD_STORE_DIR-~/.password-store/otp}
password_files=( "$prefix"/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

pass otp show -c "otp/$password" 2>/dev/null
