#!/bin/sh

# Downloads podcasts in newsboat queue file

save_directory="$HOME/downloads/podcasts"
queue_file="$HOME/.local/share/newsboat/queue"

while read -r LINE; do
    [ -z "$LINE" ] && continue
    url="$(echo "$LINE" | awk '{print $1}')"
    name="$(basename "$url")"
    id_num="$(tsp wget -P $save_directory "$url")"
    notify-send -t 2000 ""$name" enqueued."
    tsp -D "$id_num" notify-send -t 2000 ""$name" downloaded"
done < "$queue_file"

echo > "$queue_file"
