#!/usr/bin/env bash

# Searches the contents of all of the files in my lyrics directory for the
# argument word or phrase and prints the name of any matches (Artist - Title)
# If given the -p argument it will play the matched song in mpv

if [ "$1" = "-p" ] ; then
    search_string="${@: 2}"
else
    search_string="$@"
fi

result="$(grep -i -l "$search_string" ~/music/lyrics/*)"
artist_title="$(basename "$result" | sed 's/-/ - /')"

if [ "$1" = "-p" ] ; then
    song_title="$(echo "$artist_title" | awk -F- '{print $2}')"
    mpv "$(find ~/music/collection/ -iname "*$song_title*")"
else
    echo $artist_title
fi
