#!/usr/bin/env bash

# Searches the contents of all of the files in my lyrics directory for the
# argument word or phrase and prints the name of any matches (Artist - Title)
# The -p(lay) argument allows you to choose which song to play, if there are
# multiple matches, and runs the play_song script to try to find and play the
# appropriate local file.

if [ "$1" = "-p" ] ; then
    search_string="${@: 2}"
    play_song=true
else
    search_string="$@"
    play_song=false
fi

counter=0
readarray matches < <(grep -ilo "$search_string" ~/music/lyrics/*)
    for match in "${matches[@]}"
    do
        echo -e "\n$counter)" $(basename "${match}" | sed 's/-/ - /')
        (( counter=$counter + 1 ))
    done
    echo

if [ $counter = 0 ]; then
    echo -e 'No matching lyrics found\n'
    exit 0
fi

if [ $play_song = false ]; then
    exit 0
fi

if [ $counter = 1 ]; then
    selected_song=${matches[0]}
else
    echo -e 'Select which song you want to play:'
    read chosen_index
    selected_song=${matches["$chosen_index"]}
fi

play_song "$(basename "$selected_song")"
