#!/bin/sh

if pidof cmus >/dev/null ; then
    all_info=$(cmus-remote -Q)
    title=$(echo "${all_info}" | grep 'tag title' | cut -d ' ' -f3-)
    artist=$(echo "${all_info}" | grep 'tag artist' | cut -d ' ' -f3-)
    album=$(echo "${all_info}" | grep 'tag album ' | cut -d ' ' -f3-)
    shuffle_status=$(echo "${all_info}" | grep 'set shuffle' | cut -d ' ' -f3)

    # Get track position (seconds in) and duration and format for display with zero padding
    position_info=$(echo "${all_info}" | grep '^position' | cut -d ' ' -f2-)
    position_mins=$(printf "%02d" $(( position_info / 60 )))
    position_secs=$(printf "%02d" $(( position_info % 60 )))
    
    duration_info=$(echo "${all_info}" | grep '^duration' | cut -d ' ' -f2-)
    duration_mins=$(printf "%02d" $(( duration_info / 60 )))
    duration_secs=$(printf "%02d" $(( duration_info % 60 )))

    if [ "$shuffle_status" == "true" ] ; then
        shuffle_status=" 🔀"
    else
        unset shuffle_status
    fi

    track_time="$position_mins:$position_secs/$duration_mins:$duration_secs"

    echo "$title - $artist [$album] ($track_time)$shuffle_status"
fi
