#!/bin/sh

if pidof cmus >/dev/null ; then
    all_info=$(cmus-remote -Q 2>/dev/null)
    num=$(echo "${all_info}" | grep ' tracknumber ' | cut -d ' ' -f3-)
    title=$(echo "${all_info}" | grep ' title ' | cut -d ' ' -f3-)
    artist=$(echo "${all_info}" | grep ' artist ' | cut -d ' ' -f3-)
    album=$(echo "${all_info}" | grep ' album ' | cut -d ' ' -f3-)
    shuffle_status=$(echo "${all_info}" | grep ' shuffle ' | cut -d ' ' -f3)

    # Get track position (seconds in) and duration and format for display with zero padding
    position_info=$(echo "${all_info}" | grep 'position ' | cut -d ' ' -f2-)
    duration_info=$(echo "${all_info}" | grep 'duration ' | cut -d ' ' -f2-)
    position_mins=$(( position_info / 60 ))
    position_secs=$(( position_info % 60 ))
    position_formatted_mins=$(printf "%02d" $position_mins)
    position_formatted_secs=$(printf "%02d" $position_secs)
    duration_mins=$(( duration_info / 60 ))
    duration_secs=$(( duration_info % 60 ))
    duration_formatted_mins=$(printf "%02d" $duration_mins)
    duration_formatted_secs=$(printf "%02d" $duration_secs)

    if [ "$shuffle_status" == "true" ] ; then
        shuffle_status=" 🔀"
    else
        unset shuffle_status
    fi

    track_time="$position_formatted_mins:$position_formatted_secs/$duration_formatted_mins:$duration_formatted_secs"

    echo "$title - $artist [$album] ($track_time)$shuffle_status"
fi
